<script setup lang="ts">
import type { ArabicCalculator } from '~/data/calculators-ar'
import { calculatorsAr } from '~/data/calculators-ar'
const props=defineProps<{calculator:ArabicCalculator}>(),config=useRuntimeConfig()
const sitePath=useSitePath
useHead({htmlAttrs:{lang:'ar',dir:'rtl'},link:[{rel:'canonical',href:`${config.public.siteUrl}${props.calculator.path}`},{rel:'alternate',hreflang:'ar-AE',href:`${config.public.siteUrl}${props.calculator.path}`},{rel:'alternate',hreflang:'en-AE',href:`${config.public.siteUrl}${props.calculator.englishPath}`},{rel:'alternate',hreflang:'x-default',href:`${config.public.siteUrl}${props.calculator.englishPath}`}],script:[{type:'application/ld+json',innerHTML:JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity:props.calculator.faqs.map(f=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}}))})}]})
useSeoMeta({title:props.calculator.title,description:props.calculator.description,ogTitle:props.calculator.title,ogDescription:props.calculator.description,ogLocale:'ar_AE'})
const related=computed(()=>Object.values(calculatorsAr).filter(x=>x.key!==props.calculator.key))
</script>
<template>
<article class="ar-page" dir="rtl">
  <section class="hero calculator-hero"><div class="shell hero-inner hero-grid"><div class="hero-copy"><nav class="breadcrumbs"><a :href="sitePath('/ar/حاسبات-تكلفة-البناء/')">حاسبات التكلفة</a><span>/</span><span>{{ calculator.title }}</span></nav><p class="eyebrow">{{ calculator.eyebrow }}</p><h1>{{ calculator.title }}</h1><p class="lede">{{ calculator.intro }}</p><a class="hero-site-link" href="https://royalmaskan.com/">بخبرة مهندسي المسكن الملكي <span>↗</span></a></div><figure class="hero-photo"><img :src="sitePath(calculator.image)" :alt="calculator.imageAlt" width="1200" height="900" fetchpriority="high"><figcaption>المسكن الملكي · نصنع حياة ملكية</figcaption></figure></div></section>
  <div class="shell content-stack"><CostCalculatorAr :calculator="calculator"/><section class="seo-copy"><div><p class="eyebrow">خطط قبل أن تبدأ</p><h2>ماذا يعني هذا التقدير؟</h2><p>تعتمد النتيجة على المساحة والموقع ومستوى التشطيب ونطاق الأعمال. تتغير التكلفة الفعلية حسب المخططات والأعمال الإنشائية والأنظمة والموافقات وسهولة الوصول وحالة الموقع.</p><p>يراجع مهندسو المسكن الملكي التفاصيل قبل التنفيذ لتقليل التعديلات والتأخير والمفاجآت.</p></div><aside><strong>الخطوة التالية</strong><p>شارك بيانات المشروع والنتيجة مع فريقنا للحصول على مراجعة هندسية أكثر دقة.</p></aside></section><SiteCtaBanner/><section class="faq"><p class="eyebrow">الأسئلة الشائعة</p><h2>أسئلة تخطيط التكلفة</h2><details v-for="faq in calculator.faqs" :key="faq.question"><summary>{{ faq.question }}</summary><p>{{ faq.answer }}</p></details></section><section><h2>جرّب حاسبات التكلفة الأخرى</h2><div class="tool-grid"><a v-for="item in related" :key="item.key" :href="sitePath(item.path)" class="tool-card"><img :src="sitePath(item.image)" :alt="item.imageAlt" loading="lazy" width="720" height="480"><div class="tool-card-body"><span>{{ item.eyebrow }}</span><strong>{{ item.title }}</strong><p>{{ item.description }}</p></div></a></div></section></div>
</article>
</template>
