<script setup lang="ts">
import type { ArabicCalculator } from '~/data/calculators-ar'
const props=defineProps<{calculator:ArabicCalculator}>(), config=useRuntimeConfig()
const area=ref(350),quality=ref(Object.keys(props.calculator.baseRates)[1]),location=ref('sharjah'),complexity=ref(1),extras=ref(false)
const factors:Record<string,number>={sharjah:1,dubai:1.1,'abu-dhabi':1.07,ajman:.96,'abu-dhabi-city':1,yas:1.08,saadiyat:1.15,reem:1.06,mussafah:.95}
const names:Record<string,string>={sharjah:'الشارقة',dubai:'دبي','abu-dhabi':'أبوظبي',ajman:'عجمان','abu-dhabi-city':'مدينة أبوظبي',yas:'جزيرة ياس',saadiyat:'جزيرة السعديات',reem:'جزيرة الريم',mussafah:'مصفح'}
const estimate=computed(()=>area.value*props.calculator.baseRates[quality.value]*(factors[location.value]||1)*complexity.value*(extras.value?1.12:1))
const low=computed(()=>Math.round(estimate.value*.9/1000)*1000),high=computed(()=>Math.round(estimate.value*1.18/1000)*1000),months=computed(()=>Math.max(2,Math.ceil(area.value/(props.calculator.key==='construction'?90:140))))
const money=new Intl.NumberFormat('ar-AE',{style:'currency',currency:'AED',maximumFractionDigits:0})
const whatsapp=computed(()=>`${config.public.whatsappUrl}?text=${encodeURIComponent(`مرحباً المسكن الملكي، أود مراجعة تقدير ${props.calculator.title}: مساحة ${area.value} م²، والنطاق ${money.format(low.value)} إلى ${money.format(high.value)}.`)}`)
</script>
<template><section class="estimator ar-estimator"><div class="estimator-head"><div><p class="eyebrow">نموذج تقدير هندسي</p><h2>أخبرنا عن مشروعك</h2></div><div class="estimate-ref"><span>تقدير فوري</span><strong>RM · 2026</strong></div></div><div class="estimator-grid"><form class="questionnaire" @submit.prevent>
<fieldset><legend><span>١</span> بيانات المشروع</legend><div class="field-grid"><label>مساحة المشروع <small>إجمالي المساحة المشمولة بالأعمال</small><div class="input-suffix"><input v-model.number="area" type="number" min="20" max="10000" step="10"><span>م²</span></div></label><label>الموقع<select v-model="location"><template v-if="calculator.key==='fitout'"><option value="abu-dhabi-city">مدينة أبوظبي</option><option value="yas">جزيرة ياس</option><option value="saadiyat">جزيرة السعديات</option><option value="reem">جزيرة الريم</option><option value="mussafah">مصفح</option></template><template v-else><option value="sharjah">الشارقة</option><option value="dubai">دبي</option><option value="abu-dhabi">أبوظبي</option><option value="ajman">عجمان</option></template></select></label></div></fieldset>
<fieldset><legend><span>٢</span> مستوى التشطيب</legend><div class="choice-grid"><label v-for="(label,value) in calculator.qualityLabels" :key="value" class="choice" :class="{selected:quality===value}"><input v-model="quality" type="radio" :value="value"><strong>{{ label }}</strong><small>يُعدّل سعر المتر حسب جودة المواد والتفاصيل</small></label></div></fieldset>
<fieldset><legend><span>٣</span> تعقيد ونطاق الأعمال</legend><div class="field-grid"><label>مستوى التعقيد<select v-model.number="complexity"><option :value="1">أعمال اعتيادية</option><option :value="1.1">أنظمة وتفاصيل متقدمة</option><option :value="1.2">متطلبات خاصة ومعقدة</option></select></label></div><label class="toggle"><input v-model="extras" type="checkbox"><span><strong>أعمال إضافية رئيسية</strong><small>{{ calculator.key==='construction'?'مسبح أو قبو أو أعمال خارجية':calculator.key==='renovation'?'تعديلات إنشائية أو تجديد كامل للأنظمة':'موافقات ونجارة ثابتة أو أنظمة متخصصة' }}</small></span></label></fieldset>
</form><aside class="result-panel"><p class="result-label">نطاق الميزانية التقديري</p><strong class="result-total">{{ money.format(low) }}<i>إلى</i>{{ money.format(high) }}</strong><p>{{ area.toLocaleString('ar-AE') }} م² · {{ names[location] }} · {{ calculator.qualityLabels[quality] }}</p><div class="metrics"><div><span>السعر الفعلي التقديري</span><strong>{{ money.format(estimate/area) }}/م²</strong></div><div><span>المدة التقديرية</span><strong>{{ months }}–{{ months+2 }} أشهر</strong></div></div><div class="calculation-basis"><span>أساس الحساب</span><p>سعر أساسي للمتر × معامل الموقع × مستوى التعقيد والنطاق.</p></div><a class="button" :href="whatsapp" rel="noopener">راجع التقدير مع مهندس</a><small class="disclaimer">تقدير مبدئي للتخطيط وليس عرض سعر. لا يشمل الأرض وضريبة القيمة المضافة والرسوم الحكومية وأتعاب التصميم والظروف غير الظاهرة بالموقع.</small></aside></div></section></template>
